name: workflow

on:
    push:
        branches:
        - main

jobs:
    quality-check-gate-job:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code 
              uses: actions/checkout@v2

            - name: python setup
              uses: actions/setup-python@v6
              with:
                python-verion: '3.7'

            - name: install depadencies
              run: pip install -r requirements.txt

            - name: run test cases
              run: pytest --cov=calc --cov-report=term

    deploy-job:
        runs-on: ubuntu-latest
        needs: quality-check-gate-job
         
        steps:
            - name: print meessage
              run: echo "deploy job started"